# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
      web.vm.box = "ubuntu/xenial64"
      wed.vm.provider :virtualbox do |vb|
        vb.customize [ 'modifyvm', :id, '--name', 'demo-00' ]

  end
  config.vm.define "db" do |db|
      db.vm.box = "ubntu/xenial64"
      db.vm.provider :virtualbox do |vb|
        vb.customize [ 'modifyvm', :id, '--name', 'demo-00' ]
  end
end

